export const ADD_PRODUCT_ACTION = 'ADD_PRODUCT_ACTION';
export const FETCH_PRODUCTS_ACTION = 'FETCH_PRODUCTS_ACTION';
export const REMOVE_PRODUCT_ACTION = 'REMOVE_PRODUCT_ACTION';

export const ADD_CART_ITEM_ACTION = 'ADD_CART_ITEM_ACTION';
export const REMOVE_CART_ITEM_ACTION = 'REMOVE_CART_ITEM_ACTION';

export const CHANGE_PERSONAL_INFORMATION_ACTION = 'CHANGE_PERSONAL_INFORMATION_ACTION';
export const CHANGE_ADDRESS_ACTION = 'CHANGE_ADDRESS_ACTION';
export const CHANGE_CREDIT_CARD_ACTION = 'CHANGE_CREDIT_CARD_ACTION';
export const CHANGE_ORDER_STAGE_ACTION = 'CHANGE_ORDER_STAGE_ACTION';