export const ADD_PRODUCT_ACTION = 'ADD_PRODUCT_ACTION';
export const FETCH_PRODUCTS_ACTION = 'FETCH_PRODUCTS_ACTION';
export const REMOVE_PRODUCT_ACTION = 'REMOVE_PRODUCT_ACTION';

export const ADD_CART_ITEM_ACTION = 'ADD_CART_ITEM_ACTION';
export const REMOVE_CART_ITEM_ACTION = 'REMOVE_CART_ITEM_ACTION';
